<?php

use Illuminate\Database\Seeder;

class seedUserTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'username'          => 'ashique',
                'email'             => 'ashique19@gmail.com',
                'password'          => bcrypt('1234'),
                'role'              => '1',
                'firstname'         => 'md ashiqul',
                'lastname'          => 'islam',
                'name'              => 'Md Ashiqul Islam',
                'contact'           => '01710123456',
                'address'           => 'Banasree',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        => 10,
                'parmanent_address' => 'Brahmanbaria',
                'active'            => '1',
                'expiry_date'       => \Carbon::now()->addYear(1),
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '100.52',
            ],
            [
                'username'          => 'admin',
                'email'             => 'admin@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '2',
                'firstname'         => 'the admin',
                'lastname'          => 'of airposted',
                'name'              => 'The admin of airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'buyer',
                'email'             => 'buyer@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the Buyer',
                'lastname'          => 'of Airposted',
                'name'              => 'The Buyer of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'traveller',
                'email'             => 'tr@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the Traveller',
                'lastname'          => 'of Airposted',
                'name'              => 'The Traveller of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'trav2',
                'email'             => 'tr2@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the Tra2',
                'lastname'          => 'of Airposted',
                'name'              => 'The Trav2 of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'trav3',
                'email'             => 'tr3@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the Tra3',
                'lastname'          => 'of Airposted',
                'name'              => 'The Trav3 of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'b2',
                'email'             => 'b2@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the b2',
                'lastname'          => 'of Airposted',
                'name'              => 'The b2 of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            [
                'username'          => 'b3',
                'email'             => 'b3@airposted.com',
                'password'          => bcrypt('1234'),
                'role'              => '3',
                'firstname'         => 'the b3',
                'lastname'          => 'of Airposted',
                'name'              => 'The b3 of Airposted',
                'contact'           => '01710123457',
                'address'           => 'Mirpur 10',
                'city'              => 'Dhaka',
                'state'             => 'Dhaka',
                'postcode'          => '1219',
                'country_id'        =>  11,
                'parmanent_address' => 'Bangladesh',
                'active'            => '1',
                'expiry_date'       => null,
                'user_photo'        => '\public\img\users\1.png',
                'balance'           => '0',
            ],
            
        ]);
    }
}
